### PR TITLE
Rename Graph Components

### PR DESCRIPTION
**Pull request by Trjegul84**
I propose names using a more readable `adjective-noun` structure for the name of graphs, for example:
`StackedLines` instead of `MultiLines` any way they are multiple lines if they are stacked.

`LargeStackedBar` to add large and stacked adjectives before the name of the Nivo component we are using i.e Bar (ResponsiveBar). Also `SmallStackedBar` is used instead of  SmallBarStackGraph.

Since multiple small stacked bar graphic is represented in `MultiSmallBarStackGraph` then the name is changed to `MultiSmallStackedBar`

To represent only one bar, I think it is not needed to point out that it is single so `MultiSmallSingleBarGraph` could be renamed to `MultiSmallBar` only with **Bar without stacked or single. Although, it is intended to represent a graphic with multiple small bars another better option could be `SmallBars` to avoid the multi prefix and use the plural. The same for MultiSmallStackedBar another option could be SmallStackedBars.

Finally, I decided to change `MultiSmallSingleBarGraph` to `SingleSmallBars`, to imply a graph with single small bars in the sense of a group of individual bars is simpler, readable, and more understandable.

### CODE REVIEW

**Comment by erikasv** [comment]
I'm not convinced with `StackedLines`, but if @cazapatamar and @ManuelStardust agree let's go with it. I like the rest of the names.

**Comment by ManuelStardust** [comment]
I understand that these types of graphs are time series, perhaps include the word "series".

> I'm not convinced with `StackedLines`, but if @cazapatamar and @ManuelStardust agree let's go with it. I like the rest of the names.

**Comment by cazapatamar** [comment]
Sorry for the late response.

@Trjegul84 According to names you propose initially, i suggest some changes in order to standardize the way we call these components:

TimelineFootprint
StackedLines -> Lines

ForestLossPersistence
MultiSmallStackedBar -> SmallStackedBars

CurrentPAConnectivity (DPC)
SingleSmallBars -> SmallBars

NumberOfSpecies
SingleBullet -> Bullet

Below i explain why:

- I dont see necessary the word "Stacked" at "StackedLines". It has a meaning in Bar grahps but not here. Only Lines represent well the graph.
- As you did in others components, we can omit the word "Multi" in order to keep the name simple. I think it is a good idea to use "s" at the end to highlight that component has multiple lines, bars, etc.
- Also, i think we can omit using the word "Single" for the same reason. I mean, use singluar and plural by naming the components. instead of using additional adjectives.

Please let me know your opinion.

**Comment by erikasv** [comment]
I see Camilo's point, the idea is avoid `single` and `multi` and use singular and plural names, to summarize and clarify all names, the current names would be:

- LargeStackedBar -> example: current footprint
- SmallStackedBar -> example: ecosystems
- SmallStackedBars -> example: Loss and Persistence
- SmallBars -> example: connectivity - DPC 
- Pie -> example: Integrity
- Bullet -> example: number of species
- Lines -> example: historic footline

I would agree with those names

**Comment by cazapatamar** [comment]
> > MultiSmallStackedBar -> SmallStackedBars
> 
> @cazapatamar there is a problem with the name MultiSmallStackedBar ( you suggest SmallStackedBars) it is used in ForestLost is used for this group of bars: Screenshot_20220922_105849
> 
> And also we have now SmallStackedBar (before SmallBarStackGraph ) used in ecosystems, ecosystem box, ecosystems details, and ForestIntegrity. The name could be easily confused with the other.

Yes, what i propose is to change MultiSmallStackedBar by SmallStackedBars. Used at Forest LP section.

I like better using plural and singular (SmallStackedBar vs SmallStackedBars) even if the names could be similar.

It is just and opinion but if you consider still using multi and single it is also fine.

**Review by cazapatamar — APPROVED** [review]

**Pull request merged**
