### PR TITLE
Add and connect filters in indicators module

### PR DESCRIPTION
**Pull request by erikasv**

### CODE REVIEW

**Comment by Trjegul84** [comment]
Why VEBs: filed is always empty?

**Review by Trjegul84 — COMMENTED** [review]
There should be a clean filter button.

**Comment by erikasv** [comment]
> Why VEBs: filed is always empty?

@Trjegul84 Margarita said in this batch none of the indicators had that field. You made me remember that the title shouldn't be shown either.

I fond that none of the indicators has the `use` field, although some of them had it in the original data, please check the script and load the data again.

**Comment by erikasv** [comment]
> There should be a clean filter button.

Added it

**Comment by Trjegul84** [comment]
> 
@erikasv  the use field is now populated.

**Review by Trjegul84 — APPROVED** [review]

**Review by cazapatamar — APPROVED** [review]

**Review by cazapatamar — APPROVED** [review]

**Pull request merged**
