### PR TITLE
State loadingLayer = false when backbutton

### PR DESCRIPTION
**Pull request by cazapatamar**

### CODE REVIEW

**Comment by erikasv** [comment]
Please change the branch name to feature/... so the actions can run.

In some future (hopefully soon) we'll add checks for other type of branches

**Comment by cazapatamar** [comment]
> Please change the branch name to feature/... so the actions can run.
> 
> In some future (hopefully soon) we'll add checks for other type of branches

If i change the name locally and push it again, GitHub will create a new branch, right? Then, shuould i create a new PR or there is a way to link the new branch to this PR?

**Comment by erikasv** [comment]
Noup, close this one and create a new one

**Comment by cazapatamar** [comment]
Closed because the branch name is wrong according to CI definitions

**Pull request closed without merging**
