### PR TITLE
Separate compensation components

### PR DESCRIPTION
**Pull request by erikasv**

### CODE REVIEW

**Comment by cazapatamar** [comment]
Tab "Donde Como" is not working in my local env. @Trjegul84 @ManuelStardust Could you please check?

**Review by ManuelStardust — APPROVED** [review]

**Comment by Trjegul84** [comment]
> Tab "Donde Como" is not working in my local env. @Trjegul84 @ManuelStardust Could you please check?
This Tab is working on my local but when you try to download strategies an error 500 arise, also I have many errors of geoserver requests.
Look
Screenshot_20220824_085903

**Comment by Trjegul84** [comment]
Also something happend with tiles of openstreetmap when you return to "Consultas" tab.
Screenshot_20220824_090943

**Comment by erikasv** [comment]
> The only warning I have now are this: `Warning: Failed prop type: The prop `ea`is marked as required in`StrategiesBox`, but its value is `undefined`. ` and `Warning: Failed prop type: The prop `subBasin`is marked as required in`StrategiesBox`, but its value is `undefined``

I think this must be caused by corrupted data in the backend. I didn't changed any logic so it could be an old error, I'll check it out, but is out of scope of this task. If it's necessary I'll create another task

**Comment by erikasv** [comment]
> Also something happend with tiles of openstreetmap when you return to "Consultas" tab.

Unrelated bug, Please create a task and describe the steps to reproduce.

**Review by Trjegul84 — COMMENTED** [review]
A extrange behavior or routes I found when you enter to the compensations section the url is like `http://localhost:3000/GEB/Compensaciones`, and later go back to indicators section the url is
`http://localhost:3000/GEB/Indicadores` and a blank page is displayed instead of Indicators. It is not the same when you change from compensations to Monitoreo or to Portafolios

**Comment by erikasv** [comment]
> A extrange behavior or routes I found when you enter to the compensations section the url is like `http://localhost:3000/GEB/Compensaciones`, and later go back to indicators section the url is `http://localhost:3000/GEB/Indicadores` and a blank page is displayed instead of Indicators. It is not the same when you change from compensations to Monitoreo or to Portafolios

Again unrelated to this task. Create a new issue if necessary

**Review by Trjegul84 — APPROVED** [review]

**Pull request merged**
