### PR TITLE
Feature/download human footprint

### PR DESCRIPTION
**Pull request by cazapatamar**

### CODE REVIEW

**Comment by erikasv** [comment]
lgtm, but i have a question, i started using "fc" instead of "factor_de_compensacion" in the file name for the rest of the charts in compensation factor. should i use the complete name? it would match more with the names used here, but i thought it was too large

**Comment by cazapatamar** [comment]
> lgtm, but i have a question, i started using "fc" instead of "factor_de_compensacion" in the file name for the rest of the charts in compensation factor. should i use the complete name? it would match more with the names used here, but i thought it was too large

Yes,  maybe in some cases could be too long. I will change it using hh instead of the complete name.

**Comment by Trjegul84** [comment]
Then will we use the names in English?

**Comment by erikasv** [comment]
> Then will we use the names in English?

No, hh is in spanish

**Comment by cazapatamar** [comment]
> I mean, the name will be mixed with English (states ea etc) and Spanish (section name). What we chose all English or Spanish?

Good point, i have not argument for or against so what you decide it is ok for me :D

**Comment by erikasv** [comment]
I think states and ea are treated ad id, and shouldn't be translates, but if you want to, we should do it in one place, maybe export the structure from an existing file or create another as we have made in the backend

**Comment by cazapatamar** [comment]
> I think states and ea are treated ad id, and shouldn't be translates, but if you want to, we should do it in one place, maybe export the structure from an existing file or create another as we have made in the backend

According to what @erikasv said i would suggest then let the functionality name in spanish (short) and the areaType in english as it is an id and shouldn't be translated. Something like _bt_hh_states_44.csv_. What do you think? @Trjegul84

**Comment by Trjegul84** [comment]
> > I think states and ea are treated ad id, and shouldn't be translates, but if you want to, we should do it in one place, maybe export the structure from an existing file or create another as we have made in the backend
> 
> According to what @erikasv said i would suggest then let the functionality name in spanish (short) and the areaType in english as it is an id and shouldn't be translated. Something like _bt_hh_states_44.csv_. What do you think? @Trjegul84

I think It is strange the mixed languages, is better is all in English then it would be **bt_hf_states_44.csv**  We may set like this example and later we ask to the thematic group.

**Comment by cazapatamar** [comment]
> > > I think states and ea are treated ad id, and shouldn't be translates, but if you want to, we should do it in one place, maybe export the structure from an existing file or create another as we have made in the backend
> > 
> > 
> > According to what @erikasv said i would suggest then let the functionality name in spanish (short) and the areaType in english as it is an id and shouldn't be translated. Something like _bt_hh_states_44.csv_. What do you think? @Trjegul84
> 
> I think It is strange the mixed languages, is better is all in English then it would be **bt_hf_states_44.csv** We may set like this example and later we ask to the thematic group.

Ok, for now i will let in this way, all in english.

**Comment by erikasv** [comment]
ok, np

**Comment by erikasv** [comment]
But the section names are still in spanish

**Comment by cazapatamar** [comment]
> But the section names are still in spanish

Fixed!

**Review by Trjegul84 — APPROVED** [review]

**Pull request merged**
