### PR TITLE
Material migration v5

### PR DESCRIPTION
**Pull request by erikasv**
@cazapatamar @Trjegul84 @alegnaaived Please run the app and check all modules and sections, I did it myself, but just in case

### CODE REVIEW

**Comment by cazapatamar** [comment]
This error shows up by opening the subzones selector. We might need a key prop either in Autocomplete or TextField at SearchAreas component.

imagen

**Review by Trjegul84 — CHANGES_REQUESTED** [review]
Check when you go to Compensaciones >> Agregar nuevo proyecto an error is displayed
Screenshot_20220222_161913

**Comment by erikasv** [comment]
@cazapatamar Agree, names are repeated, but ids are unique, so I made a change to use ids as keys for the autocomplete component

**Comment by erikasv** [comment]
@Trjegul84 Solved, it had to do with [this](https://github.com/mui/material-ui/issues/29690#issuecomment-971673478)

**Comment by cazapatamar** [comment]
Could you please add 

> @cazapatamar Agree, names are repeated, but ids are unique, so I made a change to use ids as keys for the autocomplete component

Could you please add this solution to the modal `NUEVO PROYECTO` field `Estado del proyecto`

imagen

**Comment by erikasv** [comment]
@cazapatamar project status don't have an id, I did a workaround with the value. but the problem could reappear.

**Review by cazapatamar — APPROVED** [review]

**Review by Trjegul84 — APPROVED** [review]

**Pull request merged**
