### PR TITLE
Feature/fix nivo bug

### PR DESCRIPTION
**Pull request by Trjegul84**

### CODE REVIEW

**Comment by cazapatamar** [comment]
Why did you create a new PR?

**Comment by Trjegul84** [comment]
I thought it was needed. Should  I delete it?

**Comment by cazapatamar** [comment]
> I thought it was needed. Should I delete it?

Sorry, i didn't realize this PR was into release branch and the other PR into develop. I'm not 100% sure where this branch should be merged but I think it is only necessary to merge into release. @erikasv what do you think?

**Comment by erikasv** [comment]
> Sorry, i didn't realize this PR was into release branch and the other PR into develop. I'm not 100% sure where this branch should be merged but I think it is only necessary to merge into release. @erikasv what do you think?

Agree! I'm sorry I didn't pay enough attention, I thought the email was sent twice and didn't check the base branch or the PR I'd.

Close the other PR please (imagine my comment is in this one hehe(

**Comment by Trjegul84** [comment]
According Erika commented in the other PR 
> Forest integrity chart is broken, maybe prop names chaged.



Now the props changed in this way:  enableArcLinkLabels instead of enableRadialLabels and  enableArcLabels instead of enableSliceLabels. Now the pie is like 

Now:
Screenshot_20210503_191954

But distribution of slices is different than the one in the current release branch. The slices now are on the right side and before were to left side. Please confirm if this is it ok? 

Before:
Screenshot_20210503_191859

**Comment by cazapatamar** [comment]
Please check this case

image

**Comment by cazapatamar** [comment]
Also please check the loss and persistence section which use a similar graph. Now is disabled and pointing to mock data in the back but it is necessary also to check this graph to ensure it works well.

**Comment by erikasv** [comment]
> But distribution of slices is different than the one in the current release branch. The slices now are on the right side and before were to left side. Please confirm if this is it ok?

I don't know what you mean with `right side` and `left side`. And I don't see any change in the chart with respect to release branch.

You should rebase this branch or merge release into this one, because you create this one from develop and it's missing changes already done there.

**Comment by Trjegul84** [comment]
I've performed merge release branch into fixNivoBug branch and now the Pie looks the same with the last changes.

**Comment by Trjegul84** [comment]
> Also please check the loss and persistence section which use a similar graph. Now is disabled and pointing to mock data in the back but it is necessary also to check this graph to ensure it works well.

After reviewing that i found the ForestLossPersistence bars graph is not affected.

**Review by erikasv — APPROVED** [review]

**Pull request merged**
