### PR TITLE
Upgrade axios ~1.6.5

### PR DESCRIPTION
**Pull request by hacheG**

### CODE REVIEW

**Comment by cazapatamar** [comment]
Im getting this error in ´searchAPI.ts´. Are u guys having the same error? @ManuelStardust @hacheG 

imagen

**Comment by hacheG** [comment]
> Im getting this error in ´searchAPI.ts´. Are u guys having the same error? @ManuelStardust @hacheG
> 
> imagen

I'm reviewing

**Comment by hacheG** [comment]
> Im getting this error in ´searchAPI.ts´. Are u guys having the same error? @ManuelStardust @hacheG
> 
> imagen

image
not i'm not

**Comment by cazapatamar** [comment]
Could you please delete node_modules directory and reinstall allá dependencies, please?

**Comment by hacheG** [comment]
> Could you please delete node_modules directory and reinstall allá dependencies, please?

Done!!

**Comment by ManuelStardust** [comment]
> Im getting this error in ´searchAPI.ts´. Are u guys having the same error? @ManuelStardust @hacheG
> 
> imagen
I don't have that error either

**Review by cazapatamar — APPROVED** [review]

**Pull request merged**
