### PR TITLE
New text boxes

### PR DESCRIPTION
**Pull request by erikasv**
This includes the work done in the issues #638 and #657

### CODE REVIEW

**Comment by erikasv** [comment]
@cazapatamar @Trjegul84 You can start reviewing, and let the comments you may have, until now the new component was created, and the following sections were migrated: Ecosystems, CurrentFootprint, PersistenceFootprint.

I'll continue migrating the other sections.

**Comment by cazapatamar** [comment]
Great implementation until now. It is much more clear having a new component to handle everything related to texts and info inside each section.

**Comment by erikasv** [comment]
Guys @Trjegul84 @cazapatamar the logic is done, @CAScgutierrez will check styles tomorrow, so you can test functionality now (don't worry for conflicts, i'll solve them later)

**Comment by erikasv** [comment]
Sorry for the delay, everything is ready

**Comment by cazapatamar** [comment]
Will this information be given to us later?

image

**Comment by erikasv** [comment]
> Will this information be given to us later?

Yeah, I talked with Jaime and told him every section we needed, that's why that section has now 2 info buttons :sweat_smile:

**Comment by cazapatamar** [comment]
> > Will this information be given to us later?
> 
> Yeah, I talked with Jaime and told him every section we needed, that's why that section has now 2 info buttons sweat_smile

Great!

**Review by cazapatamar — APPROVED** [review]

**Review by Trjegul84 — COMMENTED** [review]
There is an error in the compensations module when you want to download the strategies.
I think this changes are affecting that function.

Screenshot_20220511_170639

This issue will be resolved here or in another task ?

**Comment by erikasv** [comment]
> There is an error in the compensations module when you want to download the strategies. I think this changes are affecting that function.
> ...

I can't reproduce it

**Comment by erikasv** [comment]
> > There is an error in the compensations module when you want to download the strategies. I think this changes are affecting that function.
> > ...
> 
> I can't reproduce it

But I don't think is related with this changes, I didn't modify any common component (but created a new one)

The only error I found is related with the geofences tables update.

**Comment by cazapatamar** [comment]
> There is an error in the compensations module when you want to download the strategies. I think this changes are affecting that function.
> 
> Screenshot_20220511_170639
> 
> This issue will be resolved here or in another task ?

I think this bug is not related with changes included in this PR. The download button is not working.

image

Apparently there is a field that doesn exists

image

**Comment by erikasv** [comment]
> Apparently there is a field that doesn exists

Yes, I already created a new task for it, it's related with the geofences geometries update.

I couldn't reproduce the break in the front, but tested with the same project Angela reported.

I'll merge this one, Angela can show us tomorrow what she found.

**Comment by cazapatamar** [comment]
> 

Yeah, likely it is related to geofence update data and apparently the field `id_zone` was deleted and it is used in `
Compensation`

**Pull request merged**
