### PR TITLE
Coverages fixes

### PR DESCRIPTION
**Pull request by erikasv**
Update logic related with map elements to be able to control the layers order.

### CODE REVIEW

**Comment by cazapatamar** [comment]
There is a problem with SCI layers. When tab is open the layer is loaded succesfully but when mouse over, the layer desapear.

imagen

Similar with connectivity layers. 



Also, when clic on one protected area in the graph, the others desapear. The selected protected area layer should highlight intead of desapear the others.

**Comment by erikasv** [comment]
> There is a problem with SCI layers. When tab is open the layer is loaded succesfully but when mouse over, the layer desapear.
>  ...
> Similar with connectivity layers.
> ...
> Also, when clic on one protected area in the graph, the others desapear. The selected protected area layer should highlight intead of desapear the others.

Fixed!

**Comment by cazapatamar** [comment]
If i select a pa and then change to timeline or SE tab, the layer of the select pa change color

imagen

**Review by cazapatamar — CHANGES_REQUESTED** [review]
Please check the last comment about colors in pa layers

**Comment by erikasv** [comment]
> Please check the last comment about colors in pa layers

I already fixed, but github isn't showing the last commit of the branch in this PR :sob:

**Comment by erikasv** [comment]
Done, no idea what happened :woman_shrugging:

**Review by cazapatamar — APPROVED** [review]

**Pull request merged**
