### PR TITLE
Final styles connectivity module

### PR DESCRIPTION
**Pull request by cazapatamar**

### CODE REVIEW

**Review by Trjegul84 — COMMENTED** [review]
This comment is separate from the styles because in the previous review I did't see the case when no information available message is displayed. 
I would think is right if there is no info in database to differ from case of zero protected areas but I don't know if this is what is agreed for this case. 

Screenshot_20210420_185819

**Review by Trjegul84 — APPROVED** [review]

**Comment by cazapatamar** [comment]
> This comment is separate from the styles because in the previous review I did't see the case when no information available message is displayed.
> I would think is right if there is no info in database to differ from case of zero protected areas but I don't know if this is what is agreed for this case.
> 
> Screenshot_20210420_185819

As we agreed in last friday meeting, the message of unavailable information is shown both for no data and zero values

**Review by erikasv — CHANGES_REQUESTED** [review]
Please update the spreadsheet with color palettes, complete `Gráficos o geometría a los que aplica` column and remove the ones that don't exist on `colorPalettes.js` file

**Comment by cazapatamar** [comment]
> Please update the spreadsheet with color palettes, complete `Gráficos o geometría a los que aplica` column and remove the ones that don't exist on `colorPalettes.js` file

Done

**Pull request merged**
