### PR TITLE
Forest lp graph and layers

### PR DESCRIPTION
**Pull request by cazapatamar**

### CODE REVIEW

**Comment by erikasv** [comment]
I see everything ok, but could you please add the download button to this section?

**Comment by erikasv** [comment]
Also remember to connect with the issue

**Comment by cazapatamar** [comment]
> I see everything ok, but could you please add the download button to this section?

Done!

**Comment by cazapatamar** [comment]
> Also remember to connect with the issue

Done!

**Review by erikasv — APPROVED** [review]

**Pull request merged**
